version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - "../.env.docker"
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: ../  # Adjust the build context to the parent directory
      dockerfile: ops/Dockerfile  # Specify the path to the Dockerfile
    ports:
      - "3005:${PORT}"
    volumes:
      - ../src:/usr/src/app  # Mount the src directory
      - /usr/src/app/node_modules  # Persist node_modules to avoid conflicts
    env_file:
      - "../.env.docker"
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
